export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';

export const FETCH_MEMORIES_REQUEST = 'FETCH_MEMORIES_REQUEST';
export const FETCH_MEMORIES_SUCCESS = 'FETCH_MEMORIES_SUCCESS';
export const FETCH_MEMORIES_FAILURE = 'FETCH_MEMORIES_FAILURE';

export const FETCH_MEMORY_REQUEST = 'FETCH_MEMORY_REQUEST';
export const FETCH_MEMORY_SUCCESS = 'FETCH_MEMORY_SUCCESS';
export const FETCH_MEMORY_FAILURE = 'FETCH_MEMORY_FAILURE';

export const CREATE_MEMORY_REQUEST = 'CREATE_MEMORY_REQUEST';
export const CREATE_MEMORY_SUCCESS = 'CREATE_MEMORY_SUCCESS';
export const CREATE_MEMORY_FAILURE = 'CREATE_MEMORY_FAILURE';

export const UPDATE_MEMORY_REQUEST = 'UPDATE_MEMORY_REQUEST';
export const UPDATE_MEMORY_SUCCESS = 'UPDATE_MEMORY_SUCCESS';
export const UPDATE_MEMORY_FAILURE = 'UPDATE_MEMORY_FAILURE';

export const DELETE_MEMORY_REQUEST = 'DELETE_MEMORY_REQUEST';
export const DELETE_MEMORY_SUCCESS = 'DELETE_MEMORY_SUCCESS';
export const DELETE_MEMORY_FAILURE = 'DELETE_MEMORY_FAILURE';

